config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  get 'about', to: 'about#show'

  resources :recipes

  get 'signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :chefname, presence: true, length: { maximum: 30 }

  VALID_EMAIL_REGEX= /\A[\w+\.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_many :recipes, dependent: :destroy
  has_secure_password

  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: { minimum: 4, maximum: 140 }
  belongs_to :chef
  belongs_to :recipe
  validates :chef_id, presence: true
  validates :recipe_id, presence: true
  default_scope -> {order(updated_at: :desc)}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maxiumum: 25 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_chef, :logged_in?

  def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_chef
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  before_action :set_chef, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_id] = @chef.id
      flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
      redirect_to chef_path(@chef)
    else
      render 'new'
    end
  end

  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to @chef
    else
      render 'edit'
    end
  end

  def destroy
    if !@chef.admin?
      @chef.destroy
      flash[:danger] = "Chef and all associated recipes have been deleted"
      redirect_to chefs_path
    end
  end

  private

  def chef_params
    params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
  end

  def set_chef
    @chef = Chef.find(params[:id])
  end

  def require_same_user
    if current_chef != @chef && !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own account"
      redirect_to chefs_path
    end
  end

  def require_admin
    if !logged_in? || !current_chef.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :require_admin, except: [:show, :index]

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient was successfully create"
      redirect_to @ingredient
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient name was update successfully"
      redirect_to @ingredient
    else
      render 'edit'
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def require_admin
    if !logged_in? || !current_chef.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to ingredients_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show

  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, ingredient_ids: [])
  end

  def require_same_user
    if current_chef != @recipe.chef and !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    chef = Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id] = chef.id
      flash[:success] = "You are logged in"
      redirect_to chef
    else
      flash.now[:danger] = "Incorrect user or password"
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size:80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname, class: "rounded-circle")
  end

end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/about/show.html.erb
<div class="row marketing">
        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, html: { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group row">
        <div class="control-label col-md-2">
          <%= f.label :chefname, "Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name", autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="control-label col-md-2">
          <%= f.label :email, "E-mail" %>
        </div>
        <div class="col-md-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your e-mail"%>
        </div>
      </div>
      <div class="form-group row">
        <div class="control-label col-md-2">
          <%= f.label :password %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter a password"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="control-label col-md-2">
          <%= f.label :password_confirmation, "Confirm password" %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="offset-2 col-md-10">
          <%= f.submit(@chef.new_record? ? "Create my account" : 'Update my account',
                                        class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: 'Showing all chefs' %>
<div align="center">
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
  <% @chefs.each do |chef| %>
    <ul class="listing">
      <div class="row">
        <div class="col-md-4 offset-4 items-listing">
          <li><%= link_to gravatar_for(chef), chef_path(chef) %></li>
          <li class="items-listing-title"><%= link_to chef.chefname.titleize, chef_path(chef) %></li>
          <li><small><%= pluralize(chef.recipes.count, "recipe") if chef.recipes %></small></li>
          <% if logged_in? && current_chef.admin? && !chef.admin? %>
            <li><%= link_to "Delete this chef", chef_path(chef), method: :delete,
              data: { confirm: "Are you sure you want to delete the chef and all associated recipes?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign up" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s profile" %>
<div class="row">
  <div class="col-md-4 offset-4 center">
    <%= gravatar_for @chef, size: 150 %>
  </div>
</div>
<% unless @chef.recipes.empty? %>
  <h4 align="center"> <%= @chef.chefname %>'s recipes'</h4>
  <%= will_paginate(@chef_recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
  <%= render 'recipes/recipe', obj: @chef_recipes %>
  <%= will_paginate(@chef_recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
<% else %>
  <h4 align="center">No recipes yet!</h4>
<% end %>

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, html: { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group row">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter ingredient", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="offset-2 col-md-10">
          <%= f.submit(@ingredient.new_record? ? "Create ingredient" : "Edit ingredient",
          class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>

    <% end %>
    <div class="col-md-5 offset-4 colormatch">
      [ <%= link_to "Cancel request and return to ingredients listing", ingredients_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge badge-success"><%= link_to ingredient.name, ingredient %></span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "edit ingredient name" %>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: 'Showing all ingredients' %>
<div align="center">
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
  <% @ingredients.each do |ingredient| %>
    <ul class="listing">
      <div class="row">
        <div class="col-md-4 offset-4 items-listing">
          <li class="items-listing-title"><%= link_to ingredient.name.titleize, ingredient_path(ingredient) %></li>
          <li><small><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes %></small></li>
          <% if logged_in? && current_chef.admin? %>
            <li><%= link_to "Edit this ingredient", edit_ingredient_path(ingredient) %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "create a new ingredient" %>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: @ingredient.name %>
<% unless @ingredient.recipes.empty? %>
  <h4 align="center">Recipes containing <%= @ingredient.name %> </h4>
  <%= will_paginate(@ingredient_recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
  <%= render 'recipes/recipe', obj: @ingredient_recipes %>
  <%= will_paginate(@ingredient_recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
<% else %>
  <h4 align="center">No recipes yet!</h4>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer-container py-1" style="margin-top: 2rem;">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5> <%= link_to "About", controller: "about", action: "show" %> </h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-bg" style="margin-bottom: 1rem;">
  <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Chefs', chefs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "List all recipes", recipes_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recipes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Create new recipe", new_recipe_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ingredients
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "All ingredients", ingredients_path, class: "dropdown-item" %></li>
          <% if logged_in? && current_chef.admin? %>
            <div class="dropdown-divider"></div>
            <li><%= link_to "New Ingredient", new_ingredient_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </li>
      </ul>

      <ul class="navbar-nav">
        <form class="form-inline my-2 my-lg-0", style="margin-right: 1rem;">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </ul>

      <ul class="navbar-nav navbar-right">
        <li class="nav-item">

          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_chef.chefname.split(/\s/).first.titleize %>'s profile <%= "[Admin]" if current_chef.admin? %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View your profile", chef_path(current_chef), class: "dropdown-item" %>
                <%= link_to "Edit your profile", edit_chef_path(current_chef), class: "dropdown-item" %>
                <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <% end %>
        </li>
      </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Willkomen to the app</h1>
  <h2>Recipe sharing</h2>
  <p><%= link_to "Sign up", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

<div class="show-container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>

  <hr>

</div> <!-- /container -->

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef-info center">
        <%= gravatar_for(recipe.chef, size:120) %>
      </section>
    </div>
    <div class="col-md-8 recipes">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= simple_format(truncate(recipe.description, length: 150)) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet">
          <small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.titleize %></small>
        </span>

        <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
          <div class="recipe-actions">
            <%= link_to 'Edit', edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
            <%= link_to 'Delete', recipe_path(recipe), method: :delete,
            data: { confirm: "Are you sure you want to delete this recipe?" },
             class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </p>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>

<div class="center">
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>
<%= render 'recipe', obj: @recipes %>
<div class="center">
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row justify-content-center">
  <div class="col-md-10 recipes">
    <h4 class="center description"><strong>Steps: </strong></h4>
    <%= simple_format(@recipe.description) %>
    <hr>
    <% if @recipe.ingredients.any? %>
      <p>Ingredients: <%= render @recipe.ingredients %> </p>
    <% end %>

    <div class="float-right", style="margin-right: 12px;">
      <p class="center"> <em> Created by: </em></p>
      <p class="center">
        <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
      </p>
      <p class="center">
        <div class="center"> <%= @recipe.chef.chefname.titleize %> </div>
        <div class="center" style="font-size: 12px;">
          <%= time_ago_in_words(@recipe.created_at) %> ago
        </div>
      </p>
    </div>
    <div class="recipe-actions">
      <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
        <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
        <%= link_to 'Delete', recipe_path(@recipe), method: :delete,
        data: { confirm: "Are you sure you want to delete this recipe?" },
         class: "btn btn-xs btn-danger" %>
       <% end %>
       <%= link_to "Return to listing", recipes_path, class: "btn btn-xs btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 offset-2">
      <div class="alert alert-danger">
        <h5>
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this <%= obj.class %> from being saved:
        </h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>